AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-alb

    Sample SAM app to integrate an ALB with a lambda

Parameters:
  ALBStackName:
    Type: String
    Default: aelbee

Resources:

    HelloWorldFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            FunctionName: !Sub '${AWS::StackName}-hwFunction'
            CodeUri: src/
            Handler: app.lambdaHandler
            Runtime: nodejs8.10

    MyCustomTargetGroup:
        DependsOn: HelloWorldFunction
        Type: Custom::CustomTG
        Properties:
            ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:customTargetGroup'
            Function: !Ref HelloWorldFunction 

