AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-alb

    Sample SAM app to integrate an ALB with a lambda

Parameters:
  ALBStackName:
    Type: String
    Default: aelbee
  VpcStackName:
    Type: String
    Default: veepc

Resources:

    HelloWorldFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            FunctionName: hwFunction
            CodeUri: src/
            Handler: app.lambdaHandler
            Runtime: nodejs8.10

#    LambdaTargetGroup:
#        Type: AWS::ElasticLoadBalancingV2::TargetGroup
#        Properties:
#            Name: LamdaTarget
#            TargetType: lambda
#            Port: 123
#            Protocol: TCP
#            VpcId: 
#                Fn::ImportValue: !Join [-, [vpc, Ref: 'VpcStackName', 'VpcId']]
            